# Generated by Django 4.0.1 on 2022-01-20 02:45

from django.db import migrations


def create_default_status(apps, schema_editor):
    Status = apps.get_model('todo', 'Status')
    status_list = (
        'Backlog',
        'Open',
        'Doing',
        'Done'
    )

    for status in status_list:
        status = Status(title = status)
        status.save()

def remove_default_status(apps, schema_editor):
    Status = apps.get_model('todo', 'Status')
    Status.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_status, remove_default_status)
    ]
