# Generated by Django 4.0.1 on 2022-01-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220120_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.PROTECT, to='todo.status'),
        ),
    ]
