# Generated by Django 4.0.1 on 2022-01-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(blank=True, default='2', on_delete=django.db.models.deletion.PROTECT, to='todo.status'),
        ),
    ]
